apps/contacts/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^kontakty/$', views.contact),
]

urls.py
import settings

from django.conf.urls import url, include
from django.contrib import admin

from django.views.static import serve as static_view
from apps.catalog.urls import urlpatterns as catalog_url
from apps.articles.urls import urlpatterns as articles_url
from apps.basket.urls import urlpatterns as basket_url
from apps.contacts.urls import urlpatterns as contacts_url
from apps.seo.urls import urlpatterns as seo_url
from apps.marketing.urls import urlpatterns as marketing_url


urlpatterns = [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', static_view, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', static_view, {'document_root': settings.STATIC_ROOT})
]

urlpatterns += marketing_url
urlpatterns += seo_url
urlpatterns += contacts_url
urlpatterns += basket_url
urlpatterns += articles_url
urlpatterns += catalog_url

apps/contacts/models.py
from django.db import models

# Create your models here.

class Contacts(models.Model):
    name = models.CharField("Имя", max_length=150)
    email = models.EmailField("Почта", blank=True)
    theme = models.CharField("Тема", max_length=150)
    message = models.TextField("Сообщение")
    create = models.DateTimeField("Время создания", auto_now_add=True)

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"

apps/contacts/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(label="Имя", max_length=150, widget=forms.TextInput({"class": "lp_form-input"}))
    email = forms.CharField(label="E-mail", max_length=150, widget=forms.TextInput({"class": "lp_form-input"}))
    theme = forms.CharField(label="Тема", max_length=150, widget=forms.TextInput({"class": "lp_form-input"}))
    message = forms.CharField(label="Сообщение", widget=forms.Textarea({"class": "lp_form-input"}))

apps/contacts/views.py
from django.shortcuts import render
from apps.contacts.models import Contacts
from apps.contacts.forms import ContactForm

from django.http import JsonResponse, Http404
# Create your views here.

def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = Contacts()
            contact.name = form.cleaned_data["name"]
            contact.email = form.cleaned_data["email"]
            contact.theme = form.cleaned_data["theme"]
            contact.message = form.cleaned_data["message"]
            contact.save()
            return JsonResponse({"status": "ok"})
        return JsonResponse({
                "status": "error", 
                "errors": form.errors
            })

    form = ContactForm()
    return render(request, "page/contact.html", {"form": form})

templates/page/about.html
{% extends 'index.html' %}{% block styles %}<link href="/media/css/contacts.css?v=1.000" rel="stylesheet" />{% endblock %}{% block scripts %}{% endblock %}{% block meta_keywords %}{% if meta %}{{ meta.keywords }}{% endif %}{% endblock %}
{% block meta_description %}{% if meta %}{{ meta.description }}{% endif %}{% endblock %}
{% block title %}{% if meta %}{{ meta.title }}{% endif %}{% endblock %}{%  block content %}<div class="wr_center" id="content"><div id="breadcrumbs"><ul><li><a href="/">Главная</a></li><li class="breadcrumbs_arrow">></li><li><span>О НАС</span></li></ul></div><div class="content_catalog"><h1 class="page_title">О НАС</h1><div></div></div></div>{%  endblock %}

templates/page/auction.html
{% extends 'index.html' %}{% block styles %}<link href="/media/css/contacts.css" rel="stylesheet" />{% endblock %}{% block scripts %}{% endblock %}{% block meta_keywords %}{% if meta %}{{ meta.keywords }}{% endif %}{% endblock %}
{% block meta_description %}{% if meta %}{{ meta.description }}{% endif %}{% endblock %}
{% block title %}{% if meta %}{{ meta.title }}{% endif %}{% endblock %}{%  block content %}<div class="wr_center" id="content"><div id="breadcrumbs"><ul><li><a href="/">Главная</a></li><li class="breadcrumbs_arrow">></li><li><span>ТОРГИ/АУКЦИОНЫ</span></li></ul></div><div class="content_catalog"><h1 class="page_title">ТОРГИ/АУКЦИОНЫ</h1><div></div></div></div>{%  endblock %}

templates/page/delivery.html
{% extends 'index.html' %}{% block styles %}<link href="/media/css/delivery.css?v=1.000" rel="stylesheet" />{% endblock %}{% block scripts %}{% endblock %}{% block meta_keywords %}{% if meta %}{{ meta.keywords }}{% endif %}{% endblock %}
{% block meta_description %}{% if meta %}{{ meta.description }}{% endif %}{% endblock %}
{% block title %}{% if meta %}{{ meta.title }}{% endif %}{% endblock %}{%  block content %}<div class="wr_center" id="content"><div id="breadcrumbs"><ul><li><a href="/">Главная</a></li><li class="breadcrumbs_arrow">></li><li><span>Доставка</span></li></ul></div><div class="content_catalog"><h1 class="page_title">Доставка</h1><div class="delivery"><div class="delivery_text">Получить товар Вы можете несколькими способами:</div><div class="cols__items delivery_items clearfix"><div class="col__item4 delivery_item"><div class="delivery_item-icon"><img src="/media/images/delivery/icon_shipping_self.png" /></div><div class="delivery_item-info"><div class="delivery_item-info-place">со склада в Санкт-Петербурге</div><div class="delivery_item-info-price">бесплатно</div></div></div><div class="col__item4 delivery_item"><div class="delivery_item-info"><div class="delivery_item-info-place">в пределах Санкт-Петербурга</div><div class="delivery_item-info-price">300 руб., от 5 шт. - бесплатно</div></div></div><div class="col__item4 delivery_item"><div class="delivery_item-icon"><img src="/media/images/delivery/icon_delivery.png" /></div><div class="delivery_item-info"><div class="delivery_item-info-place">по Ленинградской области</div><div class="delivery_item-info-price">по договоренности</div></div></div><div class="col__item4 delivery_item"><div class="delivery_item-info"><div class="delivery_item-info-place">по РФ</div><div class="delivery_item-info-price"><img src="/media/images/delivery/icon_delivery_services.png" /></div></div></div></div></div></div></div>{%  endblock %}

templates/page/opt.html
{% extends 'index.html' %}{% block styles %}<link href="/media/css/optom.css?v=1.000" rel="stylesheet" />{% endblock %}{% block scripts %}{% endblock %}{% block meta_keywords %}{% if meta %}{{ meta.keywords }}{% endif %}{% endblock %}
{% block meta_description %}{% if meta %}{{ meta.description }}{% endif %}{% endblock %}
{% block title %}{% if meta %}{{ meta.title }}{% endif %}{% endblock %}{%  block content %}<div class="wr_center" id="content"><div id="breadcrumbs"><ul><li><a href="/">Главная</a></li><li class="breadcrumbs_arrow">></li><li><span>Оптовые цены на картриджи</span></li></ul></div><div class="content_catalog"><h1 class="page_title">Оптовые цены на картриджи</h1><div class="optom title_bottom_line"><div class="optom_block"><h2>В нашем каталоге более 4000 позиций</h2><label>Получите прайс-лист на всю продукцию</label><a class="button lp_button_red" href="/media/files/LP_Kyocera_HP_Oki_Xerox_orig.xlsx">Скачать     </a></div></div></div></div>{%  endblock %}

templates/page/subscribe.html
{% extends 'index.html' %}{% block styles %}<link href="/media/css/contacts.css?v=1.001" rel="stylesheet" />{% endblock %}{% block scripts %}<script src="/media/js/contacts.js?v=1.001" type="text/javascript"></script><script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU"></script><script src="/media/js/map.js?v=1.000" type="text/javascript"></script>{% endblock %}{% block meta_keywords %}{% if meta %}{{ meta.keywords }}{% endif %}{% endblock %}
{% block meta_description %}{% if meta %}{{ meta.description }}{% endif %}{% endblock %}
{% block title %}{% if meta %}{{ meta.title }}{% endif %}{% endblock %}{%  block content %}<div class="wr_center" id="content"><div id="breadcrumbs"><ul><li><a href="/">Главная</a></li><li class="breadcrumbs_arrow">></li><li><span>Подписаться на рассылку</span></li></ul></div><div class="content_catalog"><h1 class="page_title">Подписаться на рассылку</h1><div class="contacts-form"><div class="order_block contacts_block-form"><div class="contacts_block-form"><form class="lp_form lp_form_field-contacts"><div class="lp_form_field"><label class="lp_form-label" for="id_email">E-mail</label>{{ form.email }}</div><div class="lp_form_field contact_form-button_send"><button class="lp_button-middle button-contact goal_form-subscribe" type="button">Подписаться</button></div></form></div></div></div></div></div>{%  endblock %}